# Generated by Django 4.2.2 on 2023-08-05 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addplayers',
            name='team',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='confirm_password',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Addplayers',
        ),
    ]
