# Generated by Django 4.2.2 on 2023-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_addplayers_team_delete_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('match', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('match', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
