# Generated by Django 4.2.2 on 2023-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merchandise_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='match',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='match',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
